version: '3.4'

services:
  balancer:
    build: ./nginx
    ports:
      - "8080:80"
    links:
      - api
    environment:
      - NGINX_PORT=80
  api:
    image: node:10-alpine
    working_dir: /home/app
    command: npm run start:compose
    volumes:
      - ./:/home/app
    ports:
      - "3000:3000"
      - "9229:9229"
    depends_on:
      - mongo
    environment:
      - DB_HOST=mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081